name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/extension-release.yml@main
    with:
      release-file-list: main.py manifest.json
      release-file-name: speedcontrol
      release-dir: SpeedControl
